<?php

/**
 * 系统权限表初始内容
 */

return [
    'table' => 'permissions',
    'keyColumn' => 'name',
    'dataColumn' => 'display_name',
    'data' => [
        'admin:index' => '后台首页',
        'admin:profile' => '个人设置',
        'custom:need-list' => '定制游需求列表',
        'custom:edit-need' => '定制游需求详情',
        'custom:handle-need-all' => '处理全部定制需求',
        'custom:handle-need' => '处理指派给自己的定制需求',
        'custom:planner-list' => '定制游规划师列表',
        'custom:add-planner' => '定制游添加规划师',
        'custom:edit-planner' => '定制游规划师详情/编辑',
        'custom:remove-planner' => '删除定制游规划师',
        'custom:case-list' => '定制游案例列表/添加案例',
        'custom:case-detail' => '定制游案例详情',
        'custom:remove-case' => '删除定制游案例',
        'member:show-list' => '前台会员列表',
        'member:item-detail-view' => '会员详情',
        'member:item-detail-edit' => '会员编辑',
        'flight:order-list' => '机票订单列表',
        'flight:order-detail' => '机票订单详情/编辑',
        'hotel:order-list' => '酒店订单列表',
        'hotel:order-detail' => '酒店订单详情/编辑',
        'tour:order-list' => '跟团游订单列表',
        'tour:order-detail' => '跟团游订单详情/编辑',
        'tour:show-list' => '跟团游产品列表',
        'tour:add-tour' => '添加跟团游',
        'tour:edit-tour' => '修改跟团游',
        'tour:remove-tour' => '删除跟团游',
        'tour:edit-detail' => '跟团游产品详情/编辑',
        'tour:checkTour'=>'跟团游产审核',
        'custom:order-list' => '定制游订单列表',
        'custom:order-detail' => '定制游订单详情/编辑',
        'ad:show-list' => '广告列表/添加广告',
        'ad:edit-detail' => '广告详情/编辑',
        'ad:remove-item' => '删除广告',
        'mice:case-list' => '会奖案例列表',
        'mice:add-case' => '添加会奖案例',
        'mice:remove-case' => '删除会奖案例',
        'mice:edit-case' => '会奖案例编辑',
        'mice:case-detail' => '会奖案例详情',
        'mice:dest-list' => '目的地列表',
        'mice:add-dest' => '添加目的地',
        'mice:dest-detail' => '目的地详情',
        'mice:edit-dest' => '目的地编辑',
        'mice:remove-dest' => '删除目的地详情',
        'mice:need-list' => '会奖需求列表',
        'mice:edit-need' => '会奖需求编辑',
        'mice:need-detail' => '会奖需求详情',
        'link:show-list' => '友情链接列表/添加友情链接',
        'link:edit-detail' => '友情链接详情/编辑',
        'link:remove-item' => '删除友情链接',
        'user:show-list' => '后台用户列表',
        'user:edit-detail' => '后台用户详情/编辑',
        'user:add-item' => '添加后台用户',
        'user:remove-item' => '删除后台用户',
        'role:show-list' => '后台角色列表',
        'role:add-item' => '添加后台角色',
        'role:edit-detail' => '后台角色详情/编辑',
        'role:grant-perm' => '后台角色权限分配',
        'role:manage-user' => '后台角色用户分配',
        'recommend:show-list' => '推荐列表',
        'recommend:add-item' => '添加推荐',
        'recommend:remove-item' => '删除推荐',
        'recommend:item-detail' => '推荐详情',
        'recommend:edit-detail' => '推荐编辑',
        'currency:show-list' => '货币列表',
        'currency:currency-detail' => '获取货币信息',
        'currency:edit-currency' => '更新货币信息',
        'currency:remove-currency' => '删除货币信息',
        'area:show-list' => '地区列表',
        'area:add-area' => '添加地区',
        'area:area-detail' => '获取地区',
        'area:edit-area' => '更新地区',
        'area:remove-area' => '删除地区',
//        'faq:show-list' => 'FAQ列表',
//        'faq:add-item' => '添加FAQ',
//        'faq:item-detail' => 'FAQ详情/编辑',
//        'faq:remove-item' => '删除FAQ',
//        'faq:category-list' => 'FAQ分类列表/添加分类',
//        'faq:category-detail' => '编辑FAQ分类',
//        'faq:remove-category' => '删除FAQ分类',
        
    ],
];